### ISSUE TITLE
polymode for working wiki files?

### ISSUE THREAD

**Issue by bbolker** [polymode/polymode#10]
There's a system called working wiki http://lalashan.mcmaster.ca/theobio/projects/index.php/Main_Page  which embeds source-file "chunks" in a Wikimedia markup language page, e.g.

http://lalashan.mcmaster.ca/theobio/projects/index.php?title=WorkingWiki/Script_Examples&action=edit

I am almost completely clueless about Emacs hacking, but I wonder how difficult it would be to adapt polymode to this case ...

**Comment by vspinu** [comment]
I am closing this due to lack of interest from other people. Markdown since took over and most of my effort goes there and into the org-mode. 

That being said, polymode has been rewritten and it's considerably simpler and much more stable now. It should be trivial to add a few regexps to build the wiki mode if there is interest.
