### ISSUE TITLE
Point randomly moves

### ISSUE THREAD

**Issue by noctuid** [polymode/polymode#166]
This is an issue that I've had for a long time. In my init file (org/elisp), the point will randomly jump somewhere without me touching the keyboard. I'll try to get a reproducible example.

**Comment by vspinu** [comment]
I fixed this yesterday. In my case the reason for this was that during auto-save I had trailing white spaces cleanup. 

The general idea goes along the following lines. If there is some function which works in the background (auto-save hooks,  timers etc) which do some changes with the one of the sibling polymode buffers and don't do `save-excursion` then that point will propagate to the current polymode buffer and you will see it as jumping randomly. This should only occur with background tasks which modify the buffer.

**Comment by vspinu** [comment]
This was fixed by synchronizing points between sibling buffers before and after every command and I wonder if there are other places where this should be done. If your problem persists then it would be really helpfull to know where it comes from. You would basically need to deactivate various packages and hooks one by one and see what's causing it. 

There is `M-x pm-debug-print-relevant-variables` which displays a bunch of relevant hooks at once (need `(require 'polymode-debug)` first.

**Comment by vspinu** [comment]
Hi @noctuid. Any updates on this one? Have you kept trying poly-org in the meanwhile?

**Comment by noctuid** [comment]
I haven't had much time recently to work with poly-org, but have encountered no further issues. I'll be working a long time in my org init file sometime, and will be able to give better feedback then.

**Comment by vspinu** [comment]
Sounds good. Thanks! I will close this one for now then.

**Comment by noctuid** [comment]
I had this issue the other day when exiting a source block (next-line) when using visual-fill-column in the source block but not in the main buffer. I will see if I can come up with a reproducible configuration.
