### ISSUE TITLE
Is polymode compatible with line-based comments instead of block-based?

### ISSUE THREAD

**Issue by shepmaster** [polymode/polymode#217]
In Rust, it's common to write Markdown inside of documentation comments, like this:

```rust
/// # Safety
///
/// This is a **safe** function!
///
/// ## Also
///
/// ```rust
/// fn main() {
///     we_write_examples_slash_tests_here_too();
/// }
/// ```
fn example() {}
```

Is polymode compatible with this style of delimiting inner code, instead of more traditional block based indicators?

I gave it a quick shot with

```emacs
(define-hostmode poly-rust-hostmode
  :mode 'rust-mode)

(define-innermode poly-rust-doc-markdown-innermode
  :mode 'markdown-mode
  :head-matcher "///"
  :tail-matcher "\n"
  :head-mode 'host
  :tail-mode 'host)

(define-polymode poly-rust-mode
  :hostmode 'poly-rust-hostmode
  :innermodes '(poly-rust-doc-markdown-innermode))
```

But it didn't *obviously* font-lock all of the markdown as I would have expected.

I also skimmed the pre-existing poly modes and the documentation, but again I didn't find anything that obviously seemed to apply to my case.

Thanks for the cool library!

**Comment by vspinu** [comment]
Polymode was designed for contiguous blocks as those are the most common. That being said, as far as the polymode functionality is concerned the prefixed blocks should work, it's the actual major mode functionality which will break because each innermode span doesn't actually see the other spans. So syntax and font-lock will surely break. Making this work would require creating a temporary buffer and stripping the comments which is orthogonal to the polymode philosophy which does 0 text copying. 

I think your best choice here is to open a helper buffer, eddit there and place back. Like org mode does it.   Have a look at `edit-indirect`.

**Comment by shepmaster** [comment]
> the actual major mode functionality which will break because each innermode span doesn't actually see the other spans

Yeah, that corresponds with what I was seeing.

> which is orthogonal to the polymode philosophy which does 0 text copying

I understand your position, but I am saddened by it. Competing solutions do not appear to have the amount of polish that polymode does — edit-indirect doesn't even have a README!

I'd love it if you'd reconsider the decision to _only_ support zero-copy situations, some day!

Thanks for the help.
