### ISSUE TITLE
Ignore tail-matcher in inner mode string literal

### ISSUE THREAD

**Issue by zonuexe** [polymode/polymode#229]
Hi, I'm working on integrating PHP and HTML templates in [poly-php](https://github.com/emacs-php/poly-php) now.
I recently started working on Polymode hacks, so I do not understand them all.

My current implementation is simple, so I can shrink the chunks with code like:

```php
<!DOCTYPE html>
<html>
  <body>
    <?php echo htmlspecialchars("The ?> is PHP's tag.", ENT_QUOTES) ?>
  </body>
</html>
```

(https://github.com/emacs-php/poly-php/issues/1)

I have prepared a workaround https://github.com/emacs-php/poly-php/pull/2 , but have some issues.

-----

Do you have best practices for this type of Polymode?

I appreciate your great work. Thank you!

**Comment by vspinu** [comment]
This seems to work:

```el

(defun poly-php-tail-matcher (_)
  (let (out)
    (while (and (null out) (re-search-forward "\\?>" nil t))
      (unless (nth 3 (syntax-ppss))
        (setq out (cons (match-beginning 0) (match-end 0)))))
    out))

(define-innermode poly-php-innermode
  :mode 'php-mode
  :head-matcher (eval-when-compile
                  (rx (or (: "<?php" word-end)
                          (: "<?=")
                          (: "<?" (or " " "\t" "\n" "\r")))))
  :tail-matcher 'poly-php-tail-matcher
  :head-mode 'body
  :tail-mode 'body)

(define-polymode poly-php-html-mode
  :hostmode 'poly-html-hostmode
  :innermodes '(poly-php-innermode))
```

But the issue is a bit tricky due to the chicken-egg dependency between syntax-ppss and the detection of chunks. Polymode needs chunks in order to reset syntax at the beggining of the span, so the use of `syntax-ppss` for span matching is an uncharted territory. Let me know if you see any issues with the above. 

I plan to implement `poly-web-mode` on top of [web-mode](http://web-mode.org/) at some point but I think web-mode doesn't support php as of now.

**Comment by vspinu** [comment]
@zonuexe ping!

php is based on c-mode which is pretty stuffy. Editing in php chunks throws currently. I will have a close look at this issue when I deal with #206.

**Comment by zonuexe** [comment]
@vspinu 
I'm sorry to leave this issue for a few months.
I fixed it according to the advice and the error no longer occurred.
Thank you so much!
