### ISSUE TITLE
Undo history might be lost after first undo with undo-tree

### ISSUE THREAD

**Issue by kurnevsky** [polymode/polymode#230]
See the discussion https://github.com/polymode/polymode/issues/214

To reproduce:
- Open [test.txt](https://github.com/polymode/polymode/files/3227453/test.txt) with `poly-markdown` mode.
- Go inside the code block and make some changes so that `buffer-undo-list` contains several elements. Don't move the point outside the block after the changes or in the process of making them.
- Execute `M-x undo-tree-undo` for first undo.
- Try to execute `M-x undo-tree-undo` again or `M-x undo-tree-redo` - nothing will work because `buffer-undo-tree` is nil. In normal situation undo-tree should transfer `buffer-undo-list` to `buffer-undo-tree` after first undo.

**Comment by vspinu** [comment]
I have added your fix to the inner hook. It's totally beyond me why this issue happens and why the workaround works. I have looked at the undo-tree code and this initialization does seem redundant, but ok. Undo tree hasn't been updated since 2014, so I guess it's not worth pocking too much into it and fixing it.

**Comment by kurnevsky** [comment]
ok, thanks for looking into this.
