### ISSUE TITLE
polymode: prefixed submode -- to support polymode in comments

### ISSUE THREAD

**Issue by slippycheeze** [polymode/polymode#265]
I would like to be able to treat the comments before functions, and in docstrings, as markdown text in a handful of modes.  In some of them that requires a prefix before every line in the submode:

```elisp
;; this should be markdown
(defun example ()
  "...and so should this."
  ;; but also this
  "polymode rocks")
```

I'm pretty sure, from reading the docs and code, that this isn't currently possible.  Of course, I'm hardly an expert having looked at polymode just now for the first time, so if I missed something please let me know.  I figure maybe some of the existing hooks or something could be used to make this happen.

If not, it'd be nice to make that happen, because "markdown in comments" along with "markdown plus some doxygen style tags" are becoming more and more required in code I write.

**Comment by vspinu** [comment]
This is very difficult due to how polymode is implemented and given current emacs capabilities. I think the best option is to have an org-style-edit-in-its-own-buffer shortcut. Or maybe have a separate buffer with the output. There is a mode somewhere that does just that. I forgot the name though. 

Same as #257
