### ISSUE TITLE
unregistered buffer warning when saving buffer in org src block

### ISSUE THREAD

**Issue by fountainer** [polymode/polymode#307]
A warning appears when saving an org mode buffer if the poly-org mode is enabled and the cursor is in a source block.
```
Warning (emacs): org-element--cache: Unregistered buffer modifications detected. Resetting.
If this warning appears regularly, please report it to Org mode mailing list (M-x org-submit-bug-report).
The buffer is:  Building Abstractions with Data.org
Current command: save-buffer
```
I reported [this bug](https://list.orgmode.org/87o86ucacp.fsf@localhost/T/#t) to the org mode mail list. One contributor find out it should be a bug of polymode (Not in the mail list. It's my first time to use a public mail list. I forgot to send a copy to the mail list). I copy them here.

> The value of after-change-functions when cursor is inside a source block is
> ```elisp
> (polymode-flush-syntax-ppss-cache
> poly-lock-after-change
> flycheck-handle-change
> t
> ws-butler-after-change)
> ```

> When outside a source block, the value is
> ```elisp
> (polymode-flush-syntax-ppss-cache
> poly-lock-after-change
> flyspell-lazy-after-change-function
> flyspell-after-change-function
> flycheck-handle-change
> org-element--cache-after-change
> t
> ws-butler-after-change)
> ```

> So, `org-element--cache-after-change' is missing. Emacs does not run
> after-change-functions in base buffer when changes are made in an
> indirect buffer.

> What you are seeing is a bug in polymode. Org element cache is trying to
> track changes in Org buffers and polymode is preventing the tracking.

**Comment by vspinu** [comment]
Should be fixed. Would appreciate if you can test it. For some reason I don't see the `org-element--cache-after-change` in my hooks. There should be some explicit action that you must have been doing in order to get it there.

**Comment by yantar92** [comment]
> Should be fixed. Would appreciate if you can test it.

The fix will not work unless you also update to latest Org on main (I
just pushed relevant change).

>  For some reason I don't see the `org-element--cache-after-change` in my hooks. There should be some explicit action that you must have been doing in order to get it there. 

You need (1) Org version from main; (2) org-element-use-cache set to t
(it is the default now, but you might explicitly set it to nil in your
config).

**Comment by vspinu** [comment]
@yantar92 I am not sure why the org-mode [change](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=5d05f5911a9078e8c77851c40dc6a77d2a4c3955) was necessary. On the polymode side the relevant fix was to run the hook inside the base buffer. https://github.com/polymode/polymode/blob/d0913ed53d27ee90b8a31b7a78a29502a5314087/polymode-core.el#L1393-L1397

It does not work by cloning hooks into indirect buffers, but rather running them in the original context. I now wonder if that does not work as expected in case of poly-org.

On my side I cannot reproduce the OP problem no matter what I try. I use org from emacs master of a few days ago (;; Version: 9.5.2). So I presume it should be enough to see the problem.

**Comment by yantar92** [comment]
> @yantar92 I am not sure why the org-mode change... was necessary. On the polymode side the relevant fix was to run the hook inside the base buffer
> It does not work by cloning hooks into indirect buffers, but rather running them in the original context. I now wonder if that does not work as expected in case of poly-org.

That was my confusion then. I only looked at your "fix" commit. I am not
familiar with polymode internals in this area.

> On my side I cannot reproduce the OP problem no matter what I try. I use org from emacs master of a few days ago (;; Version: 9.5.2). So I presume it should be enough to see the problem. 

Do you mean that you do not see `org-element--cache-before/after-change`?

Also note, that the initially reported warning is now disabled in Emacs
27 and below because we had too many false positives using our method of
"silent" change detection. In Emacs 27 and earlier, Org simply silently
trips the whole cache if the problem occurs.

If you want to forcefully enable the warning in Emacs <28, you will need
to edit org-element.el slightly. Look at the line
"(not (version< emacs-version "28"))" and change it to t.

I just tested polymode on my side with Emacs 28. I still see the
warning when I edit code blocks near begin/end lines, but not inside.

**Comment by vspinu** [comment]
> Do you mean that you do not see `org-element--cache-before/after-change`?

I do, but I don't see warnings. I am running vanilla emacs from head on all branches (master, emacs-28, emacs-27 etc) and I don't see the aforementioned error, nor I see `version<` line on emacs 27 in org-element.el. 

It could be a file layout. I am testing with these samples. 

And BTW, it's not enough to update poly-org, polymode itself should be updated.

**Comment by yantar92** [comment]
> ... I am running vanilla emacs from head on all branches (master, emacs-28, emacs-27 etc) and I don't see the aforementioned error, nor I see `version<` line on emacs 27 in org-element.el. 

That line has been added by 9843670d1 around 2 month ago. So, you are
not really using (or not loading) latest Org then.

> It could be a file layout. I am testing with these samples. 

Which samples do you refer to?

> And BTW, it's not enough to update poly-org, polymode itself should be updated. 

Sure. I simply installed fresh polymode from master for my tests.

**Comment by vspinu** [comment]
I am cloning emacs and moving to emacs-27 branch, and in the org directory these are the only occurences of emas-version

```
Grep
org-compat.el:109:(if (version< emacs-version "27")
org-compat.el:425:  "Non-nil if VERSION is lower (older) than `emacs-version'."
org-compat.el:428:  (version< version emacs-version))
org.el:4917:;; Update `customize-package-emacs-version-alist'
org.el:4918:(add-to-list 'customize-package-emacs-version-alist
ox-html.el:1324:	  emacs-version
ox.el:402:	  emacs-version
```

In any case, that's irrelevant, most likely I don't see the problem because of the sample. Sorry, forgot to add the link. Sames are part of the poly-org repo https://github.com/polymode/poly-org/tree/master/samples

I actually found a bug in the previous fix. The hooks were not run as expected. I would appreciate if you could try again and if it still does not work, could you please provide an org example where this fails for you?

**Comment by yantar92** [comment]
> I am cloning emacs and moving to emacs-27 branch, and in the org directory these are the only occurences of emas-version

You need Org mode version from Git (main branch): https://git.savannah.gnu.org/cgit/emacs/org-mode.git/log/

> In any case, that's irrelevant, most likely I don't see the problem because of the sample. Sorry, forgot to add the link. Sames are part of the poly-org repo https://github.com/polymode/poly-org/tree/master/samples
>
> I actually found a bug in the previous fix. The hooks were not run as expected. I would appreciate if you could try again and if it still does not work, could you please provide an org example where this fails for you?

It still fails. I tried one of your sample files: ob-doc-js.org, moved
point to eol in "console.log("Hello, World!");", type <RET>, M-<, and
M-: (org-element-at-point) <RET>

**Comment by vspinu** [comment]
> You need Org mode version from Git (main branch):

Wait, you are saying that I need org from git in order to reproduce the error at all? 

> I tried one of your sample files: ob-doc-js.org, moved

Nope, not on my side. With either emacs 28 or 29, no error. I presume you are 100% you are using most recent polymode. Package.el sometimes loads older versions of packages for unclear reason.

**Comment by yantar92** [comment]
> Wait, you are saying that I need org from git in order to reproduce the error at all? 

Yup. Kind of.

org-element-cache is enabled by default on main and only main has the code
that will raise warning.

Technically, the error will also happen using stable Org from ELPA, if
you enable org-element-cache. However, ELPA version of org-element-cache
is not usable because of numerous bugs. I cannot predict the exact way
how the ELPA version of the cache will be broken with polymode.

>> I tried one of your sample files: ob-doc-js.org, moved
>
> Nope, not on my side. With either emacs 28 or 29, no error. I presume you are 100% you are using most recent polymode. Package.el sometimes loads older versions of packages for unclear reason. 

Hmm. I just checked my polymode repo. It appears to be outdated and I
cannot reproduce the problem anymore after pulling the latest master.

**Comment by vspinu** [comment]
Perfect thanks! Then I consider this fixed indeed!
