### ISSUE TITLE
polymode for org mode files?

### ISSUE THREAD

**Issue by rkrug** [polymode/polymode#9]
Hi Vitalie

This looks really nice.

Do you have any plans to add support for org-mode to polymode?

I really think it would be great to be able to edit R code in an org-mode file inline and have all the ESS beauty.

Cheers,

Rainer

**Comment by codeasone** [comment]
This would be fantastic, how is the work progressing?

**Comment by vspinu** [comment]
Org is there for quite a while. Overall it works but there are some issues here and there (most notably #40). This is why I am not closing this one as yet.  

You just need to load `poly-org.el` and associate your files with `poly-org-mode` or call `poly-org-mode` in org files directly.

**Comment by codeasone** [comment]
Thanks for taking the time to post an update @vspinu

**Comment by apnewberry** [comment]
I'm very excited about this feature. Reading through the issues, it looks like it's working except that trying to do org-capture inside an org-mode polymode buffer doesn't work. Is that right? 

If so, I don't use org-capture inside org-mode very often, so that wouldn't be a major hindrance for my particular use case, so I'd be able to use ESS and python inside org-mode buffers, which would be very cool.

**Comment by vspinu** [comment]
Polymode has been rewritten and poly-org seem to be working as expected. Everyone is welcome to try it out and report issues. It now lives in its own [repo](https://github.com/polymode/poly-org).
